	TITLE	"Z33GTSFC - Z3lib 4.0"
;=================================================================
;    Copyright (C) 1989 by Jay Sage.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
; Author  : Jay Sage.
; Date    :
; Version : 1.0
; Module  : Z33GTSFC
; Abstract: This module contains the routine GETSFCB which locates
;	the Submit FCB in the Command Processor and returns its
;	address.  If SUBMIT is not enabled or if ZCPR 3.3 is not in
;	memory, the routine returns with the Z flag set.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		GETSFCB

; External References

	EXT		GETECP, SUBON

	.Z80
	CSEG
;===============================================================
; NAME - GETSFCB
; Entry: - None
; Exit :  A = 0, Zero Flag Set (Z) if NO Submit or NO ZCPR 3.3
;	      A <> 0, Zero Clear (NZ) if Valid addr in DE
;	 DE = Address of SUBMIT FCB if valid flag (Z) in AF
; Uses : AF,DE
; Special Requirements : None
;===============================================================

GETSFCB: CALL	SUBON		; Make sure SUBMIT is supported
	RET	Z		; If not, return Z
	PUSH	HL		; Save regs
	CALL	GETECP		; Get pointer to ECP
	LD	DE,11		; ..offset from ECP name
	ADD	HL,DE
	EX	DE,HL		; Move FCB address into DE
	OR	0FFH		; Return NZ to show success
	POP	HL		; ..restore regs
	RET

	END
