	TITLE	"Z33GCMDD - Z3lib 4.0
;=================================================================
;    Copyright (C) 1989 by Jay Sage.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
; Author  : Jay Sage
; Date    :
; Version : 1.0
; Module  : Z33GCMDD
; Abstract: This module contains the routine GCMDDU which examines
;	the external command file block to determine the directory
;	(drive/user) in which the file was located during the path
;	search.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		GCMDDU

; External References

	EXT		GETEFCB

	.Z80
	CSEG
;===============================================================
; NAME - GCMDDU
; Entry: - None
; Exit : BC - B=Drive (0..15), C=User (0..31) in which file located
; Uses : BC
; Special Requirements : None
;===============================================================

GCMDDU:	PUSH	HL		; Preserve registers
	PUSH	AF
	CALL	GETEFCB		; Get pointer to external FCB
	LD	BC,13		; ..offset to user value
	ADD	HL,BC
	LD	C,(HL)		; Get user number to C
	INC	HL
	LD	B,(HL)		; Get drive to B
	DEC	B		; ..shift to range 0..15
	POP	AF		; Restore regs
	POP	HL
	RET

	END
