	TITLE	"Z33PUTE3 - Z3lib 4.0"
;=================================================================
;    Copyright (C) 1989 by Jay Sage.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
; Author  : Jay Sage.
; Date    : Mar 88
; Version : 1.1
; Module  : Z33PUTE3
; Abstract: This module contains the routine PUTER3 which stores
;	the value into the Command Error Flag.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		PUTER3

; External References

	EXT		GETMSG

	.Z80
	CSEG
;===============================================================
; NAME - PUTER3
; Entry:  A - Contains the byte to store
; Exit : - None
; Uses : - None
; Special Requirements : None
;===============================================================

PUTER3:	PUSH	HL		; Preserve registers
	PUSH	AF		; ..and error code
	CALL	GETMSG		; Get message buffer address
	POP	AF		; Get error code back
	LD	(HL),A		; ..and save the byte
	POP	HL		; Restore regs
	RET

	END
