	TITLE	"Z33STPXS - Z3lib 4.0"
;=================================================================
;    Copyright (C) 1989 by Jay Sage.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
; Author  : Jay Sage
; Date    :
; Version : 1.0
; Module  : Z33STPXS
; Abstract: This module contains the routine STOPXSUB which resets
;	the XSUB input redirection flag in the Message Buffer.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		STOPXSUB

; External References

	EXT		PXSUB

	.Z80
	CSEG
;===============================================================
; NAME - STOPXSUB
; Entry: - None
; Exit : - None.  XSUB is stopped
; Uses : - None
; Special Requirements : None
;===============================================================

STOPXSUB:
	PUSH	AF		; Preserve regs
	LD	A,2		; Load flag to stop XSUB
	CALL	PXSUB		; ..and do it
	POP	AF		; Restore regs
	RET

	END
