	TITLE	"Z3MSG4 - Z3lib 4.0"
;================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from Z3MSG4.Z80 Ver 1.1 by Richard Conn
; Date    : 2 May 92
; Version : 1.3
; Module  : Z3MSG4
; Abstract: This module contains the routine PUTER2 which sets
;	the error code message byte to a specified value
; Revision:
;  1.3 -  2 May 92 - Abort if No ENV/Msg Buffer.	HFB
;  1.2 - 15 Mar 87 - Original Ver 4 Release.		HFB
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

;  Module Entry Points

	PUBLIC		PUTER2

;  External References

	EXT		GETMSG, @PUT1

	.Z80
	CSEG
;===============================================================
; NAME - PUTER2
; Entry:  A - Contains the error message byte to set
; Exit : - None.  The error message is set
; Uses : - None
; Special Requirements: None
;===============================================================

PUTER2:	PUSH	HL		;save HL
	PUSH	DE		;save DE
	PUSH	AF		;save PSW
	CALL	GETMSG		;get ptr to messages
	JR	Z,PUTE2X	;1.3 ..Exit if No Env/Msg Buffer
	LD	DE,6		;offset to code
	JP	@PUT1		; ..Offset and save byte

PUTE2X:	POP	AF		;1.3 Restore Regs
	POP	DE		;1.3
	POP	HL		;1.3
	RET			;1.3 ..and return to caller

	END
