	TITLE	"Z3PQUIET - Z3lib 4.0"
;================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from Z3PQUIET.Z80 Ver 1.1 by Richard Conn
; Date    : 15 Mar 87
; Version : 1.2
; Module  : Z3PQUIET
; Abstract: This module contains the routine PUTQUIET which sets
;	a specified value in the QUIET flag within the Z3 Envi-
;	ronment descriptor
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

;  Module Entry Points

	PUBLIC		PUTQUIET

;  External References

	EXT		@PUT0

	.Z80
	CSEG
;===============================================================
; NAME - PUTQUIET
; Entry:  A - Contains the value to set in the QUIET flag byte
; Exit : - Nothing returned, the flag is set
; Uses : - None
; Special Requirements: None
;===============================================================

PUTQUIET: PUSH	HL		;save regs
	PUSH	DE
	PUSH	AF
	LD	DE,28H		;pt to byte address
	JP	@PUT0		; ..Offset and save byte

	END
