	TITLE	"Z3QCOUT - Z3lib 4.0"
;================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from Z3QCOUT.Z80 Ver 1.1 by Richard Conn
; Date    : 8 Mar 87
; Version : 1.2
; Module  : Z3QCOUT
; Abstract: This module contains the routine QCOUT which puts
;	a specified character to CON: with control char processing
;	if QUIET flag says it is OK
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

;  Module Entry Points

	PUBLIC		QCOUT

;  External References

	EXT		GETQUIET, CCOUT

	.Z80
	CSEG
;===============================================================
; NAME - QCOUT
; Entry:  A - Contains the character to be printed to CON:
; Exit : - Nothing returned.  Char is printed if QUIET is OFF
; Uses : - None
; Special Requirements: None
;===============================================================

QCOUT:	PUSH	AF		;affect no regs
	CALL	GETQUIET	;get flag
	JR	Z,NOTQUIET	;not quiet, so print
	POP	AF		;restore PSW
	RET

NOTQUIET:
	POP	AF		;restore PSW
	JP	CCOUT		;perform normal output

	END
