	TITLE	"BCD2BIN - Convert BCD Byte in A to Binary"
;=================================================================
;  Copyright (C) 1989 by Harold F. Bower.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------

	PUBLIC	BCD2BIN		; Let this name be known

;=================================================
; Convert BCD to HEX
; Enter: A = BCD digit to be converted
; Exit : A = HEX (binary) conversion
;		 All registers preserved
;=================================================

BCD2BIN: OR	A
	RET	Z		; Zero is same
	PUSH	BC		; Save register
	LD	B,0		; Set counter
BCDBI0:	INC	B		; Bump counter
	SUB	1		; Count down BCD..
	DAA
	JR	NZ,BCDBI0	; ..til all gone
	LD	A,B
	POP	BC
	RET

	END
