;
; Generate (modified) WADE for CP/M 3
; Equate CPM3 in MONOPT.LIB must be TRUE
;
z80asm moncpm/m
z80asm monit/m
z80asm monbreak/m
z80asm montab/m
z80asm mondis/m
z80asm monsub/m
z80asm monexpr/m
z80asm monasm/m
z80asm monsym/m
z80asm monpeek/m
z80asm wade/m
;
link wsid=wade
link monrsx=moncpm,monit,monbreak,montab,mondis,monsub,monexpr,monasm,monsym,monpeek[op]
;
era monrsx.rsx
rename monrsx.rsx=monrsx.prl
gencom wsid monrsx
;
