;
; Generate (modified) WADE for CP/M 3
; Equate CPM3 in MONOPT.LIB must be TRUE
;
m80 =moncpm/v/e
m80 =monit/v/e
m80 =monbreak/v/e
m80 =montab/v/e
m80 =mondis/v/e
m80 =monsub/v/e
m80 =monexpr/v/e
m80 =monasm/v/e
m80 =monsym/v/e
m80 =monpeek/v/e
m80 =wade/v/e
;
link wsid=wade
link monrsx=moncpm,monit,monbreak,montab,mondis,monsub,monexpr,monasm,monsym,monpeek[op]
;
era monrsx.rsx
ren monrsx.rsx=monrsx.prl
gencom wsid monrsx
