;
; test video funcs
;
; link to DarkStar Monitor symbols...
include	Common.inc.asm
include	darkstar.equ


	ORG	TPA
	JP	BEGIN

include	zdsvid.lib


BEGIN:
	LD	HL,MS1
	CALL	DISPWT
	; AT HOME
	CALL	ZDHOMNC
	LD	HL,MS2
	CALL	DISPWT
	; AT HOME CLEAR
	CALL	ZDHOME
	LD	HL,MS3
	CALL	DISPWT
	; PRINT, SCROLL
; 	LD	B,$30
; PST:	LD	HL,MS4
; 	CALL ZDDSPNL
; 	LD	A,B
; ; 	CALL	H2AJ2
; 	DJNZ	PST
; 	LD	HL,MS5
; 	CALL	DISPWT
	; attributes
	CALL	ZDHOME
	LD	HL,AMSN
	CALL	ZDDSP
	CALL	BLNKON
	LD	HL,AMSB
	CALL	ZDDSP
	CALL	BLNKOF
	CALL	REVON
	LD	HL,AMSR
	CALL	ZDDSP
	CALL	REVOF
	CALL	UNDRON
	LD	HL,AMSU
	CALL	ZDDSP
	CALL	UNDROF
	CALL	HLITON
	LD	HL,AMSH
	CALL	ZDDSP
	CALL	HLITOF
	CALL	GRPHON
	LD	HL,AMSG
	CALL	ZDDSP
	CALL	GRPHOF
	CALL	DISPWT
	; CURSOR OFF
	CALL	CRSROF
	LD	HL,MS6
	CALL	DISPWT

	; CURSOR ON
	CALL	CRSRON
	LD	HL,MS7
	CALL	DISPWT

	LD	H,0
	LD	L,0
	CALL	SETCUR
	LD	HL,MS0000
	CALL	ZDDSP

	LD	H,2
	LD	L,2
	CALL	SETCUR
	LD	HL,MS0202
	CALL	ZDDSP

	LD	H,10
	LD	L,10
	CALL	SETCUR
	LD	HL,MS1010
	CALL	DISPWT

EXIT:
; 	JP	JBOOT
	RET
	;;
	;; ROUTINES
	;;
	;
	; SHOW MSG, WAIT USER
DISPWT:	CALL	ZDDSP
	CALL	ZDDSPNL
	CALL	GCHR
	RET
	;
SETCUR:
	PUSH	BC
	LD	C,ESC
	CALL	BBCONOUT
; X address
	LD	A,L
	ADD	A,32
	LD	C,A
	CALL	BBCONOUT
; Now the Y value
	LD	A,H
	ADD	A,32
	LD	C,A
	CALL	BBCONOUT
; terminate
	LD	C,0
	CALL	BBCONOUT
	POP	BC
	RET

	;
	; msgs...
MS1:	DEFB	"PRESS A KEY TO BEGIN",$00
MS2:	DEFB	"AT HOME NO CLEAR...",CR,LF,$00
MS3:	DEFB	"AT HOME WITH CLEAR...",CR,LF,$00
MS4:	DEFB	"ROW PRINT & SCROLL TEST ",$00
MS5:	DEFB	"PRINT,SCROLL END...",CR,LF,$00
MS6:	DEFB	"CURSOR OFF...",CR,LF,$00
MS7:	DEFB	"CURSOR ON...",CR,LF,$00
MS8:	DEFB	"40 COLUMN MODE...",CR,LF,$00
MS9:	DEFB	"80 COLUMN MODE...",CR,LF,$00
MS10:	DEFB	"CRT HARD RESET...",CR,LF,$00
MS0000:	DEFB	"@ POSITION 0,0",CR,LF,$00
MS0202:	DEFB	"@ POSITION 2,2",CR,LF,$00
MS1010:	DEFB	"@ POSITION 10,10",CR,LF,$00


MS99:	DEFB	"TEST END.",CR,LF,$00

AMSN:	DEFB	"> QUESTO E' NORMAL <",CR,LF,$00
AMSB:	DEFB	"> QUESTO E' BLINKING <",CR,LF,$00
AMSR:	DEFB	"> QUESTO E' REVERSE <",CR,LF,$00
AMSU:	DEFB	"> QUESTO E' UNDERLINE <",CR,LF,$00
AMSH:	DEFB	"> QUESTO E' HIGHLIGHT <",CR,LF,$00
AMSG:	DEFB	"> QUESTO E' GRAPHIC < (GRAPHIC)",CR,LF,$00
; 	DEFB	"> ",$1B,$0F,$0D,"QUESTO E' BIT 5 (UNKN)",$1B,$0E,$0D," <",CR,LF	;,$00
; 	DEFB	"> ",$1B,$11,$0D,"QUESTO E' BIT 6 (UNKN)",$1B,$10,$0D," <",CR,LF	;,$00
; 	DEFB	"> ",$1B,$1E,$0D,"QUESTO E' BIT 7 (UNKN)",$1B,$1D,$0D," <",CR,LF,$00

	END
