	TITLE	"Z33FCB1C - Z3lib 4.0"
;=================================================================
;    Copyright (C) 1989 by Jay Sage.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
; Author  : by Jay Sage.
; Date    :
; Version : 1.0
; Module  : Z33FCB1C
; Abstract: This module contains the routine FCB1CHK which checks
;	the first default File Control Block to see if the token
;	parsed there was a valid file specification.  If there was
;	an error (signalled by a non-zero value in the record-count
;	byte), then this routine returns a non-zero value.  A zero
;	value signals a valid FCB.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
;  Module Entry Points

	PUBLIC		FCB1CHK

; Definitions

FCB1	EQU	005CH		; Primary default FCB

	.Z80
	CSEG
;===============================================================
; NAME - FCB1CHK
; Entry: - None
; Exit :  A = 0, Zero flag Set (Z) if FCB has valid name
;	      A <> 0, Zero Clear (NZ) if error
; Uses : AF
; Special Requirements : None
;===============================================================

FCB1CHK: LD	A,(FCB1+15)	; Get the record count byte
	OR	A		; ..and set flags
	RET

	END
