	TITLE	"Z33GTSRU - Z3lib 4.0"
;=================================================================
;    Copyright (C) 1989 by Jay Sage.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
;  Author  : Jay Sage.
;		modified for Z3LIB common code by Harold F. Bower
;  Date	   : 19 Jan 88
;  Version : 1.0
;  Module  : Z33GTSRU
;  Abstract: This module contains the routine GETSRUN which deter-
;	mines whether or not a SUBMIT job is currently running.
;  Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		GETSRUN

; External References

	EXT		GETMSG, @GET1

; Definitions

OFFSRUN	EQU	2DH		; Offset to SUBMIT running flag

	.Z80
	CSEG
;===============================================================
; NAME - GETSRUN
; Entry: - None
; Exit :  A = 0, Zero Flag Set (Z), if NO SUBMIT job running
;	      A <> 0, Zero Flag Clear (NZ) if SUBMIT running
; Uses : AF
; Special Requirements : None
;===============================================================

GETSRUN: PUSH	HL		; Preserve registers
	PUSH	DE
	CALL	GETMSG		; Get message buffer address
	LD	DE,OFFSRUN	; ..offset to Submit Running flag
	JP	@GET1		; Get the flag and exit

	END
