	TITLE	"Z33GDEFD - Z3lib 4.0"
;=================================================================
;    Copyright (C) 1989 by Jay Sage.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
; Author  : Jay Sage.
; Date    :
; Version : 1.0
; Module  : Z33GDEFD
; Abstract: This module contains the routine GDEFDU which gets
;	the values of the current default (logged) Drive/User
;	Area by reading the CURDR and CURUSR bytes in the message
;	buffer.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		GDEFDU

; External References

	EXT		GETMSG

; Definitions

OFFCUSR	EQU	2EH		; Offset to Current User Byte

	.Z80
	CSEG
;===============================================================
; NAME - GDEFDU
; Entry: - None
; Exit : BC - B = Current Drive (A=0), C = Current User Area
; Uses : BC
; Special Requirements : None
;===============================================================

GDEFDU:	PUSH	HL		; Preserve registers
	PUSH	AF
	CALL	GETMSG		; Get pointer to start of message buffer
	LD	BC,OFFCUSR	; ..and offset to current User Byte
	ADD	HL,BC
	LD	C,(HL)		; Get User number to C
	INC	HL
	LD	B,(HL)		; Get Drive to B (drive A = 0)
	POP	AF		; Restore regs
	POP	HL
	RET

	END
