	TITLE	"Z33RTCST - Z3lib 4.0"
;=================================================================
;    Copyright (C) 1989 by Jay Sage.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
; Author  : Jay Sage
; Date    :
; Version : 1.0
; Module  : Z33RTCST
; Abstract: This module contains the routine RETCST which returns
;	the address of the command status flag.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		RETCST

; External References

	EXT		GETMSG

	.Z80
	CSEG
;===============================================================
; NAME - RETCST
; Entry: - None
; Exit : HL - Points to the Command Status Flag
; Uses : HL
; Special Requirements: None
;===============================================================

RETCST:	PUSH	AF
	CALL	GETMSG		; Point to message buffers
	INC	HL		; ..and advance to Command Status Flag
	INC	HL
	INC	HL
	POP	AF		; Restore rest of regs
	RET			; ..and return with address of CSF

	END
