	TITLE	"Z3GCL2	- Z3LIB	4.3a"
	NAME	('Z3GCL2')
;================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;----------------------------------------------------------------
; Author  : Richard Conn
; Date	  :
; Version : 1.1
; Module  : Z3GCL2
; Abstract: This module contains the routine GETCL2 which returns
;	the address of the next command in the command line buffer
;	and the first character in that command.
; Revision: 1.2
;	Shortened code by calling GETCL1.
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

;  Module Entry Points

	PUBLIC	GETCL2

;  External References

	EXT	GETCL1

	.Z80
	CSEG
;===============================================================
; NAME - GETCL2
; Entry: - None
; Exit : Found: A = 1st char in command, Zero Flag Reset (NZ)
;	     HL - Address of next command in Command Line Buffer
;	 Not Found: A = 0 and Zero Flag Set (Z)
; Uses : AF,HL
; Special Requirements: None
;===============================================================
;	cmdline:
;		dw	<address of next char to process>
;		db	<size of buffer>
;		db	<dummy used for BDOS READLN fct char cnt>
;		db	<chars in command line>
;		db	0

GETCL2:
	CALL	GETCL1		; Point HL to Z3CL

	LD	A,(HL)		; Get NXTCHR pointer in HL
	INC	HL
	LD	H,(HL)
	LD	L,A		; HL pts to next char

	LD	A,(HL)		; Get the char in A (Null or ';')
	OR	A		; Set Zero Flag if no more chars
	RET

	END
