	TITLE	"Z3GPATH - Z3lib 4.0
;================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from Z3GPATH.Z80 Ver 1.1 by Richard Conn
; Date    : 15 Mar 87
; Version : 1.2
; Module  : Z3GPATH
; Abstract: This module contains the routine GETPATH which
;	returns a pointer to the ZCPR3 External path, and the
;	maximum allowable number of entries
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

;  Module Entry Points

	PUBLIC		GETPATH

;  External References

	EXT		@GET2

	.Z80
	CSEG
;===============================================================
; NAME - GETPATH
; Entry: - None
; Exit : HL - pointer to external path if found
;	  A <> 0 and Zero Flag Reset (NZ) if OK
;	       A = 0 and Zero Flag Set (Z) if Error/Not Present
; Uses : AF,HL
; Special Requirements: None
;===============================================================

GETPATH: PUSH	DE		;save DE
	LD	DE,9		;pt to path entry
	JP	@GET2		; Get indexed 16 and 8-bit values

	END
