	TITLE	"Z3MSG1 - Z3lib 4.0"
;---------------------------------------------------------------;
; Copyright (C) 1987, By Jay Sage
; Author  : Jay Sage
; Date    :
; Version : 1.0
; Module  : Z3MSG1
; Abstract: This module contains the routine GETER1 which
;	returns the error flag message
; Revision: This module replaces original Z3MSG1 for compatability
;	with ZCPR3.3.
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

;  Module Entry Points

	PUBLIC		GETER1

;  External References

	EXT		GETERC

	.Z80
	CSEG
;===============================================================
; NAME - GETER1
; Entry: - None
; Exit : A = 0, Zero Set (Z) if No Error command present
;	     A <> 0, Zero Clear (NZ) if Error
; Uses : AF
; Special Requirements: None
;===============================================================

GETER1:	PUSH	HL		;save HL
	CALL	GETERC		;get ptr to error command line
	POP	HL
	RET

	END
