22 April 1988

Dear Reader,

In  a fit of exuberance and expectation, I reported  in  NEWEI.WS
certain  material  errors.   My apologies  to  Frank  Gaude'  and
Echelon, Inc. and to you.

Specifically, I am NOT taking over Echelon, Inc.  My statement to
that effect was in error and the result of a misunderstanding  on
my   part.   I  also  presumed,  in  error,  to  report   Frank's
retirement.

Frank  and I are negotiating only for certain assets of  Echelon,
mainly its software products.  This negotiation is still going on
and may be complete in a week or so.

In  the interest of accuracy and good business practice,  I  will
have  no  more to say on the subject until our  negotiations  are
complete.  At that time we will make a proper announcement.

Please  disregard all of NEWEI.WS and if you are a sysop,  please
remove it from your system.  Thank you very much.

Again, my sincere apologies.

Joe Wright
