;	TITLE	"SEPRINT - Syslib 4.0"
	NAME	('EPRINT')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Richard Conn
; Date    :
; Version : 1.1
; Module  : SEPRINT
; Abstract:  This module contains the routine EPRINT which is an
;	Inline print function to the CON: device without any
;	control character interpretation.  It prints the Null-
;	terminated text string immediately following the CALL to
;	EPRINT until the ending Null is encountered, and resumes
;	execution with the next byte after the Null.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		EPRINT

; From SYSLIB Get..

	EXT		EPSTR

	.Z80
	CSEG
;===============================================================
; NAME - EPRINT
; Entry: (Stack) - contains starting address of Null-terminated str
; Exit : - Nothing returned, the string is printed
; Uses : - None
; Special Requirements: None
;===============================================================

EPRINT:	EX	(SP),HL		; HL = Adr, Old HL on stack
	CALL	EPSTR		; Print string pted to by HL
	EX	(SP),HL		; Restore HL and New Ret Adr
	RET

	END
