;	TITLE	"SFEXIST - Syslib 4.0"
	NAME	('FEXIST')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SFEXIST.Z80 Ver 1.2 by Richard Conn
; Date    : 23 Jul 89
; Version : 1.4
; Module  : SFEXIST
; Abstract: This module contains the routine F$EXIST which
;	determines if a specified file exists on the currently
;	logged drive.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		F$EXIST

; From SYSLIB Get..

	EXT		@BDOSA

; Definitions

F$SRC1	EQU	17		; CP/M, Zrdos, P2Dos Search First Fcn

	.Z80
	CSEG
;===============================================================
; NAME - F$EXIST
; Entry: DE - Addresses the FCB for the desired file
; Exit :  A = 0, Zero Flag Set (Z) If NOT Found
;		A <> 0, Zero Flag Reset (NZ) if Found
; Uses : AF
; Special Requirements: None
;===============================================================

F$EXIST: LD	A,F$SRC1	; Search for First File Occurance
	CALL	@BDOSA		; ..working in other module
	INC	A		; FF --> 0 if Not Found
	RET

	END
