;	TITLE	"SFMAKE - Syslib 4.0"
	NAME	('FMAKE')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SFMAKE.Z80 Ver 1.2 by Richard Conn
; Date    : 4 Jul 89
; Version : 1.4
; Module  : SFMAKE
; Abstract: This module contains the routine F$MAKE which creates
;	a file of the specified name on the currently logged disk.
; Revision:
;	1.5  10 Dec 89  Joe Wright
;	Ensure directory code is returned and Z flag set on
;	successful MAKE.
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		F$MAKE

; External References

	EXT		@BDOSA, F$DELETE

; Definitions

B$MAKE	EQU	22		; CP/M, Zrdos, P2Dos Make File Fcn

	.Z80
	CSEG
;===============================================================
; NAME - F$MAKE
; Entry: DE - Addresses the FCB for the desired file
; Exit :  A = Directory Code if Successful Create
;	      A = 0FFH if Unable to Create file (error)
; Uses : AF
; Special Requirements: None
;===============================================================

F$MAKE:	CALL	F$DELETE	; Delete File
	LD	A,B$MAKE	; Set File Create Function
	CALL	@BDOSA		; ..do Dos work in other module
	RET	M		; No directory space (NZ)
	CP	A		; Retain directory code (Z)
	RET

	END
