;	TITLE	"SGUA - Syslib 4.0"
	NAME	('GUA')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Richard Conn
; Date    :
; Version : 1.1
; Module  : SGUA
; Abstract: Get currently logged User Number returning it in
;		  Register A.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points:

	PUBLIC		GUA

; Data Definitions:

BDOS	EQU	5		; CP/M, Zrdos, P2Dos Entry Point
BSUA	EQU	32		; Get/Set User Area Command

	.Z80
	CSEG
;=========================================================================
; NAME - GUA - Get currently logged User Number to Register A
; Entry: None
; Exit :  A = User Number, Flags have no meaning
; Uses : AF
; Special Requirements:  None
;=========================================================================

GUA:	PUSH	BC		; Save Regs
	PUSH	DE
	PUSH	HL
	LD	E,0FFH		; Get User
	LD	C,BSUA		; set user function
	CALL	BDOS
	POP	HL		; Restore Regs
	POP	DE
	POP	BC
	RET

	END
