;	TITLE	"SMA3DC - Syslib 4.0"
	NAME	('MA3DC')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;	 	Derived from SMADC.Z80 by Richard Conn
; Date    : 6 Jul 89
; Version : 1.3
; Module  : SMA3DC
; Abstract: This module contains the routine MA3DC which prints
;	the byte in the A register as 3 decimal characters to memory.
;	Leading Zeros are printed.  No registers are altered.
; Revision:
;	1.4  9 Dec 89  Joe Wright
;	Use common code in SMAFDC.
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		MA3DC

; From SYSLIB get..

	EXT		@ADM1

	.Z80
	CSEG
;===============================================================
; NAME - MA3DC
; Entry:  A = Byte to print
;	 DE - Points to three-byte memory buffer
; Exit : DE - Points to byte after the buffer
; Uses : DE
; Special Requirements: None
;===============================================================

MA3DC:	PUSH	BC
	LD	B,1		; Store leading zeroes
	JP	@ADM1		; Go to common code in SMAFDC

	END
