;	TITLE	"SMHLDC - Syslib 4.0"
	NAME	('MHLDC')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SMHL5DC.Z80 by Richard Conn
; Date    : 11 Jun 89
; Version : 1.3
; Module  : SMHLDC
; Abstract: This module contains the routine MHLDC which saves
;	the contents of the HL register pair in a five character
;	field to a Memory buffer.  Leading zeros are saved as
;	spaces.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		MHLDC

; From SYSLIB Get..

	EXT		MHLD

	.Z80
	CSEG
;===============================================================
; NAME - MHLDC
; Entry: HL - Contains the number to be printed
;	 DE - Points to a 5-byte buffer
; Exit : DE - Points to character after the buffer
; Uses : DE
; Special Requirements: None
;===============================================================

MHLDC:	PUSH	BC		; Save the BC Register pair
	LD	B,0		; B = 0 for Leading <sp>
	JP	MHLD		; ..and continue in another module

	END
