;	TITLE	"SMOVE0 - Syslib 4.0"
	NAME	('HMOVB')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SMOVE.Z80 Ver 1.1 by Richard Conn
; Date    : 11 Jun 89
; Version : 1.3
; Module  : SMOVE0
; Abstract: This module contains the routine HMOVB which moves up
;	to 256 bytes of data in memory.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		HMOVB

; From SYSLIB Get..

	EXT		MOVEB

	.Z80
	CSEG
;===============================================================
; NAME - HMOVB
; Entry: HL - Points to the first byte of source block
;	 DE - Points to the first byte of destination block
;	  B - Number of bytes to move
; Exit : HL - Points to the byte after last source byte
;	 DE - Points to the byte after last destination byte
; Uses : DE,HL
; Special Requirements: None
;===============================================================

HMOVB:	CALL	MOVEB		; Do the move
	PUSH	BC		; Save BC
	LD	C,B		; BC = B
	LD	B,0
	ADD	HL,BC		; HL pts to byte after last byte moved
	EX	DE,HL
	ADD	HL,BC		; DE pts to byte after last byte moved
	EX	DE,HL
	POP	BC		; Get BC
	RET

	END
