;	TITLE	"SSCRLF - Syslib 4.0"
	NAME	('SCRLF')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SSCRLF.Z80 Ver 1.1 by Richard Conn
; Date    : 17 Sep 89
; Version : 1.2
; Module  : SSCRLF
; Abstract:  This module contains the routine SCRLF which sends a
;	Carriage Return/Line Feed combination to the CON: and/or the
;	LST: device(s) depending on the value of the SCTLFL public byte.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		SCRLF

; From SYSLIB Get..

	EXT		SCTLFL, CRLF, LCRLF

	.Z80
	CSEG
;===============================================================
; NAME - SCRLF
; Entry: - None
; Exit : - Nothing returned, the CRLF is printed
; Uses : - None
; Special Requirements: None
;===============================================================

SCRLF:	PUSH	AF		; Save A and Flags
	LD	A,(SCTLFL)	; Get Control Flag
	RLA			; LST:?
	CALL	C,LCRLF
	AND	02H		; CON: bit shifted?
	CALL	NZ,CRLF
	POP	AF		; Restore A and Flags
	RET

	END
