;	TITLE	"SSHL4HC - Syslib 4.0"
	NAME	('SHL4HC')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Richard Conn
; Date    :
; Version : 1.1
; Module  : SSHL4HC
; Abstract: This module contains the routine SHL4HC which prints
;	the contents of the HL register as 4 Hexidecimal charac-
;	ters on the CON: or LST: devices.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		SHL4HC

; From SYSLIB Get..

	EXT		SA2HC

	.Z80
	CSEG
;===============================================================
; NAME - SHL4HC
; Entry: HL - Value to be printed
; Exit : - Nothing returned, the characters are printed
; Uses : - None
; Special Requirements: None
;===============================================================

SHL4HC:	PUSH	AF		; Save A
	LD	A,H		; Print H
	CALL	SA2HC
	LD	A,L		; Print L
	CALL	SA2HC
	POP	AF		; Restore A
	RET

	END
