;	TITLE	"SSPRINT - Syslib 4.0"
	NAME	('SPRINT')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Richard Conn
; Date    :
; Version : 1.1
; Module  : SSPRINT
; Abstract: This module contains the routine SPSTR which prints
;	the specified string to the CON: and/or LST: as specified
;	in the switched output byte
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		SPRINT

; From SYSLIB Get..

	EXT		SPSTR

	.Z80
	CSEG
;===============================================================
; NAME - SPRINT
; Entry: (Stack) - Contains address of string start
; Exit : - Nothing returned.  Execution resumes at byte after
;	    terminating 0 of string.
; Uses : - None
; Special Requirements: None
;===============================================================

SPRINT:	EX	(SP),HL		; HL = Adr, Old HL on stack
	CALL	SPSTR		; Print String pted to by HL
	EX	(SP),HL		; Restore HL and new Ret Adr
	RET

	END
