;	TITLE	"SUD1 - Syslib 4.0"
	NAME	('GETPUD')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SUD1/SUD2/SUD3.Z80 by Richard Conn
; Date    : 17 Sep 89
; Version : 1.2
; Module  : SUD1
; Abstract: This module contains the routines PUTUD and GETUD
;	which save the currently logged drive and user area to a
;	local buffer, and restore them from the local buffer,
;	respectively.  The user must insure that PUTUD is called
;	before GETUD, otherwise the drive and user will be set to
;	unknown values.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		PUTUD, GETUD

; From SYSLIB Get..

	EXT		RETUD, LOGUD

	.Z80
	CSEG
;===============================================================
; NAME - PUTUD
; Entry: - None
; Exit : - Nothing returned.  CUSER & CDISK contain curr DU:
; Uses : - None
; Special Requirements: None
;===============================================================

PUTUD:	PUSH	BC		; Save The BC pair
	CALL	RETUD		; Get the current Disk and User
	LD	(CUSER),BC	; ..and Save locally
	POP	BC
	RET

;===============================================================
; NAME - GETUD
; Entry: - None
; Exit : - Nothing returned.  DU: set to CUSER & CDISK contents
; Uses : - None
; Special Requirements: None
;===============================================================

GETUD:	PUSH	BC		; Save the BC pair
	LD	BC,(CUSER)	; Get Saved User & Disk
	CALL	LOGUD		; ..and Set them
	POP	BC
	RET

; Data Storage/Buffers

	DSEG			; Put these in Data Segment

CUSER:	DEFS	1		; Current User
CDISK:	DEFS	1		; Current Disk

	END
