===========================================================================

                                 n/SYSTEMS
                           21460 Bear Creek Road
                            Los Gatos, CA 95030
                              (408) 354-7188

===========================================================================
06/15/91



                                 Í Ä É Ó Ë


        Á fasô ± megabytå RAÍ disë foò youò AMPRÏ Z8° Littlå Board¡

Witè ± megabytå oæ RAÍ chipó no÷ widelù availablå foò undeò $60¬ thió ió á 
greaô timå foò AMPRÏ Z8° Littlå Boarä useró tï instalì aî MDISË RAÍ disk¡  
MDISË ió aî add-oî RAÍ disë boarä foò thå AMPRÏ Z8° Littlå Boarä thaô 
provideó spacå foò uğ tï ± megabytå oæ 256ë dynamiã RAÍ chipó thaô arå useä 
aó á soliä statå disë drive®  

MDISË provideó á fasô anä responsivå RAÍ workspacå environmenô tï speeä uğ 
disk-intensivå operationó likå wordprocessing¬ databaså access¬ modeí filå 
transfer¬ prograí developmenô anä alì otheò filå accesó operationó bù 
reducinç thå timå requireä foò disë read/writå operations®  No÷ yoõ caî 
reaä oò writå tï RAÍ disë fileó aô RAÍ memorù speeds.  Adä MDISË tï aî all-
floppù systeí foò especiallù dramatiã anä usefuì improvementó iî speeä anä 
productivity®  

Becauså programó residenô oî MDISË arå accesseä aô memorù speeds¬ alì youò 
often-useä utilitieó oî MDISË becomå 'memory-resident'¬ eliminatinç thå 
neeä tï wastå TPÁ witè extensivå ZCPR³ RCĞ segments® Thå transienô versionó 
oæ youò Ú utilitieó no÷ operatå aó quicklù aó thå mucè morå limiteä 
versionó residenô iî youò RCP®  Witè ARUNZ.COÍ (renameä tï CMDRUN.COM© anä 
ALIAS.CMÄ alsï residenô oî MDISK¬ yoõ alsï caî havå á fulì rangå oæ instanô 
aliaseó aô youò fingertips.

Iæ yoõ haven'ô yeô useä á systeí witè á RAÍ disë workspace¬ you'rå reallù 
missinç something®  Yoõ maù think¬ aó É firsô did¬ thaô it'ó toï mucè 
troublå tï loaä á RAÍ disë witè youò commonlù useä utilitieó eacè timå yoõ 
turî oî youò computer¬ buô ZCPR³ aliaseó anä thå fasô copù utilitù ACOPÙ 
(included© makå thå wholå procesó automatiã, whilå thå ZCPR³ filå searcè 
patè allowó yoõ tï accesó occasionallù useä utilitieó withouô copyinç theí 
tï MDISK®  Eveî iæ you'rå currentlù usinç á harä disk¬ you'lì sooî geô sï 
useä tï thå ne÷ speeä anä responsivenesó oæ utilitieó operatinç oî MDISË 
anä thå feeì oæ 'elbo÷ room§ oî youò MDISË workspacå thaô you'lì wondeò ho÷ 
yoõ eveò goô alonç withouô it!


  o  MDISË ió á 5.75¢ ø 5.25¢ printeä circuiô boarä thaô plugó 
     intï youò AMPRÏ Z8° socket®  Youò Z8° chiğ plugó intï á 
     sockeô oî thå MDISË board®  Board-to-boarä spacinç ió 1/2¢ 
     witè aî overalì totaì heighô oæ ± 1/4¢ (7/8¢ board-to-boarä Š     spacinç is requireä wheî alsï usinç á SMARTCLOCK.©   

  ï  Yoõ pluç uğ tï 3² standarä Japaneså 256ë dynamiã RAÍ chipó
     intï thå socketó provideä oî MDISË foò uğ tï ± megabytå oæ 
     extendeä RAM®  

  ï  Thå MDISË driveò softwarå enableó thå extendeä RAÍ tï bå
     useä aó á soliä statå disë drive¬ completå witè á systeí
     tracë foò instanô warí boots®  Thå driveò softwarå ió 
     supplieä aó á boot-timå utilitù foò uså witè standarä AMPRÏ 
     systems¬ includinç extendeä ZCPR³ systemó anä NZCOÍ (usinç 
     thå currenô BIOÓ versioî 3.¸ oò thå ne÷ experimentaì BIOÓ 
     versioî 3.9© thaô automaticallù installó thå MDISË driveró 
     intï thå memorù imagå oæ thå BIOÓ jusô belo÷ thå ZCPR³ 
     buffers®  Theù dï noô wastå TPÁ bù loadinç undeò thå CCP®  
     Sourcå codå foò thå BIOÓ driveò insertó ió alsï includeä foò 
     custoí installatioî intï youò AMPRÏ BIOÓ sourcå code.

  ï  MDISË also includeó aî extendeä RAÍ tesô utility®

  o  MDISË requireó 5vdã viá á standarä disë drivå poweò 
     connector.

  o  NOTEº  Iî ordeò tï uså MDISK¬ youò Littlå Boarä musô bå 
     modifieä tï replacå thå eighô 64ë RAÍ chipó witè thå 1¶ piî 
     DIĞ socketó wå providå anä tï adä onå jumper®  Iæ yoõ caî 
     uså á solderinç iron¬ thió ió aî easù modificatioî anä 
     doesn'ô affecô normaì operatioî oæ thå Littlå Board®  
     Completå instructionó arå included®  

     Iæ yoõ feeì uneasù abouô workinç oî youò Littlå Board¬ 
     n/SYSTEMÓ caî arrangå tï dï thå modificatioî foò yoõ aô 
     nominaì cost.


Thå MDISË RAÍ disë boarä (Nï RAÍ chipó arå supplied)¬ includinç thå manuaì 
anä softwarå disk¬ ió onlù $12¹ pluó $µ s/h®  Californiá residentó pleaså 
adä saleó tax®  Shippinç ió viá prioritù mail®  UPÓ COÄ ió aî additionaì 
$5®  Orderó witè accompanyinç checë oò moneù ordeò arå normallù shippeä thå 
samå daù theù arå received®  

Foò thoså oæ yoõ whï prefeò tï builä thingó yourselveó oò wanô tï builä á 
modifieä MDISË RAÍ disë board¬ perhapó foò uså witè non-AMPRÏ systems¬ 
n/SYSTEMÓ offeró á barå MDISË printeä circuiô boarä alonç witè alì 
documentation¬ includinç aî MDISË manual¬ schematic¬ partó lisô anä 
softwarå disk foò onlù $29¬ including shipping.

===========================================================================
