; ASMDDT.JOB - ASseMble DDTz as a JOB
; for use with M80/L80 on same disk.  Assemble 3 files, 2 relocatable
; NOTE:  DO NOT USE /M switch with M80!
m80 =ccinstal
m80 =ddtdisa
m80 =ddtz
l80 ccinstal,ccinstal/n/e
l80 /p:0,ddtdisa,ddtz,ddtzero/n/e
l80 /p:100,ddtdisa,ddtz,ddtone/n/e
;-i ddtzero.com  (do this when DDTZ is up, below)
;-r 100  (loads 0-based image)
;-d 203 204  (displays length of program:  lo byte, hi byte)
;-i ddtone.com  (set up to load 0100-based image)
;-r mmnn  (mm = 1 + hi-byte value from above, nn = lo-byte value)
;-i temp.com
;-k  (saves temporary autoload file)
;-^C  (CTRL-C to exit and reset CCP)
; WAIT FOR DDTZ to finish loading (and JOB to continue)
ddtz ccinstal.com
temp
UP