TITLE DU90HELP - Help pages for DU-90
.xlist
.z80
cseg

PUBLIC	HELP
EXT	ILPRT,PROMPT
CR	EQU	13
LF	EQU	10
;
;
;**********************************************************************
;
;			    Help Guide
;
;**********************************************************************
;
HELP:
	CALL	ILPRT
	DB	CR,LF,LF,'Operands in brackets [...] are optional'
	DB	CR,LF,'Numeric values: ''n'' are decimal, ''x'' hex'
	DB	CR,LF,'Prefixing numeric entry with ''#'' accepts the'
	DB	' alternate notation'
	DB	CR,LF,LF
	DB	'+[x]     step in [x] sectors',CR,LF
	DB	'-[x]     step out [x] sectors',CR,LF
	DB	'#        print disk parameters for current drive',CR,LF
	DB	'=Abc     search for ASCII Abc from current sector',CR,LF
	DB	'             caution: upper/lower case matters',CR,LF
	DB	'             use <xx> for hex:',CR,LF
	DB	'                 to find "IN 0" use: =<db><0>     or'
	DB	CR,LF
	DB	'                 "(tab)H,0(CR)(LF)" use: =<9>H,0<D><A>'
	DB	CR,LF
	DB	'{        save 4 current sectors into memory buffer',CR,LF
	DB	'}        restore 4 saved sectors',CR,LF
	DB	'<        save current sector into memory buffer',CR,LF
	DB	'>        restore saved sector',CR,LF
	DB	'(        toggle map display of erased files',CR,LF
	DB	'?        help (displays this guide)',CR,LF
	DB	'A[ff,tt(hex)] ASCII dump',CR,LF
	DB	'B[nn]    Boot track number of sectors per track'
	DB	CR,LF,LF,LF,LF,LF
	DB	'[More]'
	DB	1,CR,'       ',CR,LF,CR,LF
	DB	'CHANGE:',CR,LF,CR,LF
	DB	'CHaddress,byte,byte... (hex)',CR,LF
	DB	'CAaddress,data...  (ASCIIx',CR,LF
	DB	'         <xx> Allowed for imbedded hex',CR,LF
	DB	'CHfrom-through,byte, e.g. CH0-7F,E5',CR,LF
	DB	'CAfrom-through,byte',CR,LF
	DB	'D[ff,tt(hex)] Dump (hex+ASCII)',CR,LF
	DB	'Fn.t     Find file',CR,LF
	DB	'F        Find next extent of n.t above',CR,LF
	DB	'Gxx      CP/M Allocation Group xx',CR,LF
	DB	'H[ff,tt(hex)] hex dump',CR,LF
	DB	'K[du:]filename[.ext]  Dump sequential memory to disk'
	DB	CR,LF
	DB	'L        Log in drive',CR,LF
	DB	'LX       Log in drive X',CR,LF
	DB	'M[xx]    Map [from group xx]'
	DB	CR,LF,LF,LF,LF,LF,LF,LF,LF
	DB	'[More]'
	DB	1,CR,'       ',CR,LF,CR,LF
	DB	'N        New disk',CR,LF
	DB	'O        1''s complement 512 byte sector',CR,LF
	DB	'P        Printer toggle switch',CR,LF
	DB	'Q        Quiet mode (no msgs)',CR,LF
	DB	'R        Read current sector',CR,LF
	DB	'Snn      Sector nn',CR,LF
	DB	'Tnn      Track nn',CR,LF
	DB	'Unn      User nn for Find command',CR,LF
	DB	'V[xx]    View [xx] ASCII sectors',CR,LF
	DB	'W        Write current sector',CR,LF
	DB	'X        Exit program',CR,LF
	DB	'Y        Yank current sector into sequential memory'
	DB	CR,LF
	DB	'Z[xx]    Sleep [xx tenths]',CR,LF
	DB	'/[nn]    Repeat [nn (decimal) times]'
	DB	CR,LF,LF,LF,LF,LF,LF,LF,LF,LF,LF
	DB	'[More]'
	DB	1,CR,'       ',CR,LF,LF,LF,LF,LF,LF,LF
	DB	'Cancel a function with C or Ctl-C',CR,LF
	DB	'Suspend output with S or Ctl-S',CR,LF
	DB	'Separate commands with ";"',CR,LF
	DB	'         Example: G0',CR,LF
	DB	'         +;D;Z#20;/',CR,LF
	DB	'             would step in, dump, sleep 2 seconds'
	DB	CR,LF
	DB	'             and repeat until  CTL-C is typed',CR,LF
	DB	'All numeric entries except  "B", "S", "T", "U" & "/" are hex'
	DB	CR,LF
	DB	'             (use #nn for decimal)'
	DB	CR,LF,LF,LF,LF,LF
	DB	'(See DU.DOC for complete examples)'
	DB	CR,LF,LF,LF,LF,0
	JP	PROMPT
END
