;	TITLE	"SBDOS - Syslib 4.0"
	NAME	('BDOS')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		derived from SBDOS.Z80 Ver 1.1 by Richard Conn
; Date    : 4 Jul 89
; Version : 1.3
; Module  : SBDOS
; Abstract: This module contains the routines BDOS and @BDOS which
;	effect a call to the Basic Disk Operating System.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

; Module Entry Points

	PUBLIC		BDOS, @BDOS

; Definitions

BDOSE	EQU	5		; CP/M, Zrdos, P2Dos Entry Point

	.Z80
	CSEG
;===============================================================
; NAME - BDOS
; Entry:  C - Contains BDOS Function Number to execute
;	 DE - Contains optional parameters (1-byte args in E)
; Exit : AF - Status of the operation (See Operating System specs)
; Uses : AF,HL
; Special Requirements: None
;===============================================================

@BDOS:				; Alternate Library Module entry point
BDOS:	PUSH	DE		; Save Registers
	PUSH	BC
	CALL	BDOSE		; Make Call
	POP	BC		; Restore Regs
	POP	DE
	OR	A		; Set Status Flags
	RET

	END
