;	TITLE	"SCRLF - Syslib 4.0"
	NAME	('CRLF')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Richard Conn
; Date    :
; Version : 1.1
; Module  : SCRLF
; Abstract:  This module contains the routine CRLF which prints
;	a Carriage Return/Line Feed combination to the CON: device.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		CRLF

; From SYSLIB Get..

	EXT		COUT

; Definitions

LF	EQU	10		; Line Feed char
CR	EQU	13		; Carriage Return char

	.Z80
	CSEG
;===============================================================
; NAME - CRLF
; Entry: - None
; Exit : - Nothing returned, the CR/LF combination is printed
; Uses : - None
; Special Requirements: None
;===============================================================

CRLF:	PUSH	AF		; Save Reg A and Flags
	LD	A,CR		; Print <CR>
	CALL	COUT
	LD	A,LF		; Print <LF>
	CALL	COUT
	POP	AF		; Restore Reg A and Flags
	RET

	END
