;	TITLE	"SFDELETE - Syslib 4.0"
	NAME	('FDELET')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Modified from SFDELETE.Z80 Ver 1.1 by Richard Conn
; Date    : 11 Jun 89
; Version : 1.3
; Module  : SFDELETE
; Abstract: This module contains the routine F$DELETE which will
;	Remove disk directory references to the specified file
;	via BDOS calls.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		F$DELETE

; From SYSLIB Get..

	EXT		@DOS

; Definitions

B$DEL	EQU	19		; CP/M, Zrdos, P2Dos Delete Fcn

	.Z80
	CSEG
;===============================================================
; NAME - F$DELETE
; Entry: DE - Addresses the FCB for the desired file
; Exit :  A = 0 and Zero Flag Set (Z) if OK
;		A <> 0 and Zero Flag Reset (NZ) if File Not Found
; Uses : AF
; Special Requirements: None
;===============================================================

F$DELETE: LD	A,B$DEL		; Set Delete Function
	JP	@DOS		; ..go to other module to work

	END
