;	TITLE	"SFWRITE - Syslib 4.0"
	NAME	('FWRITE')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SFWRITE.Z80 Ver 1.2 by Richard Conn
; Date    : 11 Jun 89
; Version : 1.4
; Module  : SFWRITE
; Abstract: This module contains the routine F$WRITE which writes
;	the sector addressed by the current DMA address to the
;	specified file using sequential write
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		F$WRITE

; From SYSLIB Get..

	EXT		@BDOSA

; Definitions

B$RECW	EQU	21		; CP/M, Zrdos, P2Dos Seq Write Fcn

	.Z80
	CSEG
;===============================================================
; NAME - F$WRITE
; Entry: DE - Addresses the FCB for the desired file
; Exit :  A = 0 and Zero Flag Set (Z) if Ok
;	      A <> 0 and Zero Flag Reset (NZ) if Error
; Uses : AF
; Special Requirements: None
;===============================================================

F$WRITE: LD	A,B$RECW	; Set File Write Function
	JP	@BDOSA		; ..and do work in other module

	END
