;	TITLE	"SISALNUM - Syslib 4.0"
	NAME	('ISALNU')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SISALNUM.Z80 Ver 1.1 by Richard Conn
; Date    : 28 Jul 89
; Version : 1.3
; Module  : SISALNUM
; Abstract: This module contains the single routine ISALNUM
;	which returns the Zero Flag Set (Z) if the character
;	passed in register A is a digit or alphabetic ASCII
;	character.  If not, The Zero Flag is Reset (NZ).
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points:

	PUBLIC		ISALNUM

; From SYSLIB Get..

	EXT		ISDIGIT, ISALPHA

	.Z80
	CSEG
;=========================================================================
; NAME - ISALNUM
; Entry: A = Character to be evaluated
; Exit : A = Character, Zero Flag Set (Z) if ASCII Number or Alphabetic
;		 Zero Flag Reset (NZ) if NOT
; Uses : F
; Special Requirements:  None
;=========================================================================

ISALNUM: CALL	ISDIGIT		; Is it a Digit?
	RET	Z		; ..Return with flags properly set if so
	JP	ISALPHA		; Else jump to check for alpha & set flags

	END
