	TITLE	"SVERSION - Syslib 4.x"
	NAME	('VERSIO')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; SYSLIB Vers 4 is derived from SYSLIB 3.6 by Richard Conn & others
;     This module contains the basic primative routines.
; Author  : Harold F. Bower
; Date	  : 29 Aug 92
; Version : 4.5
; Module  : SVERSION
; Abstract: This lists the changes to the library and reports
;	the current version
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
;  Module Entry Points

	PUBLIC		VERSION

; Definitions

VERS	EQU	45		; Version Number
subver	equ	' '		; Bug fix letter

	PAGE
	.Z80
	CSEG
;===============================================================
; NAME - VERSION
; Entry: - None
; Exit : HL - Contains the Major version # (H) and Minor (L)
; Uses : HL
; Special Requirements: None
;===============================================================

; Date   : 29 Aug 92  Public Release
; Version: 4.5
; Revised: Harold F. Bower
; Changes: Corrected SOUT to preserve flags per documentation.

; Date	 : 15 Jun 91  Public Release
; Version: 4.4
; Revised: Harold F. Bower/Joe Wright
; Changes: Included new SORT routines from Joe Wright, re-combined to
;	one library.			HFB

; Date   : 12 Dec 90   Public release of SYSLIB 4.3c
; Version: 4.3c
; Revised: Harold F. Bower/Joe Wright
; Changes: Split Syslib into a Basic primative library (This one, SLIB0)
;	  and one with routines for building tools and applications (SLIB1)

; Date	 : 25 Nov 90
; Version: 4.3b
; Revised: Harold F. Bower/Joe Wright
; Changes: Completely rewrote SORT routine, Multiply and Divide, fixed
;	   ARGV and corrected COUT7 MSB stripping (JWW), pared 2 bytes
;	   from GFA per Howard Goldstein, modified DIRALPHA, DIRQ and
;	   DIRQS to use SORT (HFB).

; Date	 : 29 Sep 90
; Version: 4.3a
; Revised: Harold F. Bower
; Changes: Fixed errors in SORT and incorporated ideas from Carson Wilson.

; Date	 : 18 Aug 90
; Version: 4.3
; Revised: Harold F. Bower/Joe Wright
; Changes: Fixed EVALxx routines, added optimizations of JWW.

; Date	 : 28 Oct 89
; Version: 4.2a
; Revised: Harold F. Bower
; Changes: Bug fixes, generalized for assembly/linkage by ZMAC and
;	   SLR family of tools.

; Date	 : 23 Sep 89
; Version: 4.2
; Revised: Harold F. Bower
; Changes: Additional Optimization of BDOS & BIOS Interfaces.  Split
;	   into increased number of modules to reduce linked pgm size.

; Date	 : 23 Jul 89
; Version: 4.1 (Test)
; Revised: Harold F. Bower
; Changes: Significant rewrites and Optimizations

; Date	 : 1 Apr 89
; Version: 4.0 (release)
; Revised: Harold F. Bower
; Changes: Minor Code Optimizations and cosmetic source polishing

; Date	 : 19 Dec 88
; Version: 4.0
; Revised: Harold F. Bower
; Changes: Fixed bug in SCOMP, Added more checks to LUINIT, Saved
;	   a byte, deleted lib call & speeded up INITFCB, Added
;	   Extent mask back in DPARAMS & SDIR02.

; Date	 : 7 Aug 88
; Version: 4.0
; Revised: Harold F. Bower
; Changes: Optimized SDIR01-04,10, SDIRBF.  Added DMA set to 80H to
;	   SDIR, SDIRQ and SDIRQS.

; Date	 : 14 May 88
; Version: 4.0
; Revised: Harold F. Bower
; Changes: Revised 16-bit comparisons in several modules.

; Date	 : 19 Jan 88
; Version: 4.0
; Revised: Harold F. Bower
; Changes: Corrected DIRQ bug, minor additional optimization.  Final release

; Date	 : 2 Aug 87
; Version: 4.0
; Revised: Harold F. Bower
; Changes: Fixed reported test bugs.  Initial optimized release

; Date	 : 24 Apr 87
; Version: 3.7
; Revised: Harold F. Bower
; Changes: Optimized routines for Z80 Code, corrected errors, crunched code

; Date	 : 10 Dec 85
; Version: 3.6
; Revised: Richard Conn
; Changes: Z80 mnemonics, many minor

; Previous Version: 1.0 (16 Jan 84)
;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

VERSION: LD	HL,VERS/10*256+VERS MOD 10	; Load BCD Vers #
	RET

;  Identifying Text

	DEFB	'SYSLIB '
	DEFB	VERS / 10 + '0','.',VERS MOD 10 + '0',subver,' 10 Aug 92'
	DEFB	' (C) 1989-92 by Alpha Systems Corp.',0

	END
