;;
;;Zex script to convert Z33ZAS.Z80 for assembly by ZASM
;;

finrep24 zcpr33.z80 z33zasm.z80 /b/ $^i,"maclib" "*include"
finrep24 z33zasm.z80 /b/ "makepath" "mkpath"
finrep24 z33zasm.z80 /b/ "callproglf" "callpglf"
finrep24 z33zasm.z80 /b/ "extmpathadr" "extmptha"
finrep24 z33zasm.z80 /b/ "nextcmd" "nxtcmd"
finrep24 z33zasm.z80 /b/ "scantype" "scantyp"

;
;
;
;The file has been prepared for ZASM.
;
;strike return
^?
