	TITLE	"VID2 - Vlib 4.1"
	NAME	('VID2')
;================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from VID2.Z80 Ver 1.1 by Richard Conn
; Date	  : 12 Jan 89
; Version : 1.2
; Module  : VID2
; Abstract:  This module contains the routine EREOL which clears
;	the line on which the cursor is positioned, from the cur-
;	rent position to the end of the line.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

; Module Entry Points

	PUBLIC		EREOL

; ..From VLIB Get..

	EXT		@SETV0, @CE, @EOLD

	.Z80
	CSEG
;===============================================================
; EREOL - Erase to End-Of-Line
;  Entry: - None
;  Exit :  A = 0 and Zero Flag Set (Z) if done
;	   A <> 0 and Zero flag Reset (NZ) if Erase Ok
;  Uses : AF
; Special Requirements: None
;===============================================================

EREOL:	PUSH	HL		; Save regs
	LD	A,(@EOLD)	; Load EREOL delay from table
	LD	HL,(@CE)	; Get address of Clear to EOL string
	JP	@SETV0		; Finish up elsewhere (in VID1)

	END
