;	TITLE	"SFCLOSE - Syslib 4.0"
	NAME	('FCLOSE')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SFCLOSE.Z80 Ver 1.1 by Richard Conn
; Date    : 11 Jun 89
; Version : 1.3
; Module  : SFCLOSE
; Abstract: This module contains the routine F$CLOSE which
;	performs a BDOS file closing of the specified file.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		F$CLOSE

; ..from SYSLIB Get..

	EXT		@DOS

; Definitions

B$CLOS	EQU	16		; CP/M, ZRDOS, P2DOS Close File Fcn

	.Z80
	CSEG
;===============================================================
; NAME - F$CLOSE
; Entry: DE - Addresses the FCB for the desired operation
; Exit :  A = 0 and Zero Flag Set (Z) if Successful Close
;	      A = 0FFH, Zero Flag Reset (NZ) if Error
; Uses : AF
; Special Requirements: None
;===============================================================

F$CLOSE: LD	A,B$CLOS	; Set Close Function
	JP	@DOS		; ..jump to other module to do it

	END
