;	TITLE	"SLA2HC - Syslib 4.0"
	NAME	('LA2HC')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SLA2HC.Z80 by Richard Conn
; Date    : 28 Oct 89
; Version : 1.3
; Module  : SLA2HC
; Abstract: This module contains the routine LA2HC which prints
;	the character in register A as two Hexidecimal characters
;	on the currently logged LST: device.  All registers and
;	flags are preserved.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry points

	PUBLIC		LA2HC

; From SYSLIB Get..

	EXT		LOUT, @B2HH, @B2HL

	.Z80
	CSEG
;===============================================================
; NAME - LA2HC
; Entry: A - Contains the byte to be printed
; Exit : - No status or values returned
; Uses : - None
; Special Requirements: - None
;===============================================================

LA2HC:	PUSH	AF		; Save the A register
	CALL	@B2HH		; Convert High Nybble to Hex
	CALL	LOUT		; ..and print
	POP	AF		; Restore A reg for Low Nybble print
	PUSH	AF		; Save the A register
	CALL	@B2HL		; Convert low nybble to Hex Char
	CALL	LOUT		; ..and list it
	POP	AF		; Restore A
	RET

	END
