;	TITLE	"SMHL4DC - Syslib 4.0"
	NAME	('MHL4DC')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SMHL5DC.Z80 by Richard Conn
; Date    : 11 Jun 89
; Version : 1.3
; Module  : SMHL4DC
; Abstract: This module contains the routine MHL4DC which stores
;	the contents of the HL register pair in a four character
;	field to a Memory buffer.  Leading zeros are always stored.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		MHL4DC

; From SYSLIB Get..

	EXT		MHL4

	.Z80
	CSEG
;===============================================================
; NAME - MHL4DC
; Entry: HL - Contains the number to be printed
;	 DE - Points to a 4-byte buffer
; Exit : DE - Points to character after buffer
; Uses : DE
; Special Requirements: None
;===============================================================

MHL4DC:	PUSH	BC
	LD	B,1
	JP	MHL4

	END
