;	TITLE	"SMTH09 - Syslib 4.0"
	NAME	('XORHD')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Richard Conn
; Date    : 2/8/87
; Version : 1.1
; Module  : SMTH09
; Abstract: This module contains the routine SMTH09 which performs
;	an Exclusive-OR of two 16-bit values passed in regusters,
;	and returns the result
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		XORHD

	.Z80
	CSEG
;===============================================================
; NAME - XORHD
; Entry: HL,DE - Contain 16-bit values to be XORed
; Exit : HL - Contains the result
; Uses : HL
; Special Requirements: None
;===============================================================

XORHD:	PUSH	AF		; Save A and Flags
	LD	A,L		; Do low byte
	XOR	E
	LD	L,A
	LD	A,H		; Do high byte
	XOR	D
	LD	H,A
	POP	AF		; Restore A and Flags
	RET

	END
