;	TITLE	"SMTH01 - Syslib 4.0"
	NAME	('ADDHD')
;=================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;-----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from SMTH01.Z80 Ver 1.1 by Richard Conn
; Date    : 17 Sep 89
; Version : 1.2
; Module  : SMTH01
; Abstract: This module contains the routine ADDHD which adds
;	the contents of two 16-bit registers, returning a flag
;	if overflow occured.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		ADDHD

	.Z80
	CSEG
;===============================================================
; NAME - ADDHD
; Entry: HL,DE - Contain two 16-bit unsigned values
; Exit :  F - Carry Set (C) if Overflow, else Reset (NC)
;	 HL - Contains (HL)+(DE)
; Uses : F,HL
; Special Requirements: None
;===============================================================

ADDHD:	ADD	HL,DE		; Carry is set by this command
	RET

	END
