ERASE
? CHR(22)
SET DEFAULT TO B:
SET COLON OFF
SET TALK OFF
RESTORE FROM PGMASK
POKE 71,255
USE PGFILE
@  1,0  SAY CHR(201)+$(LDEMO,1,78)+CHR(202)
@  2,0  SAY GABBIA
@  3,0  SAY GABBIA
@  4,0  SAY GABBIA
@  5,0! SAY CHR(195)+$(LDEMO,1,78)+CHR(196)
@  6,0  SAY GABBIA
@  7,0  SAY GABBIA
@  8,0  SAY GABBIA
@  9,0  SAY GABBIA
@ 10,0  SAY GABBIA
@ 11,0  SAY GABBIA
@ 12,0  SAY GABBIA
@ 13,0  SAY GABBIA
@ 14,0  SAY GABBIA
@ 15,0  SAY GABBIA
@ 16,0  SAY GABBIA
@ 17,0  SAY GABBIA
@ 18,0  SAY GABBIA
@ 19,0  SAY CHR(195)+$(LDEMO,1,78)+CHR(196)
@ 20,0  SAY GABBIA
@ 21,0  SAY GABBIA
@ 22,0  SAY GABBIA
@ 23,0  SAY GABBIA
@ 24,0  SAY CHR(199)+$(LDEMO,1,78)+CHR(200)
? CHR(23)
@  0,0  SAY " "
@  1,0  SAY CHR)201)
@  2,65 SAY "DATA:"+DATE()
@  2,1  SAY " VERSIONE 1.03   AUTORE: PIERGIORGIO BETTI  (C) 21/04/86"
POKE 40,245
@  3,31 SAY "ARCHIVIO PROGRAMMI"
POKE 40,255
@  0,13 SAY "MODO:"
@  0,28 SAY "REC:"
@  4,2  SAY "MS-DOS  CP/M 86-80  NE-DOS"
@  4,57 SAY "*(PGB SOFTWARE SYS. *"
STORE "#" TO CICLO1
STORE $(LATERALI,1,62)+CHR(240) TO FONDO1
DO WHILE CICLO1="#"
DO PGOVR1
DO PGOVR2
@ 10,8  SAY $(FONDO,1,63)
@ 11,8  SAY FONDO1
@ 12,8  SAY FONDO1
@ 13,8  SAY FONDO1
@ 14,8  SAY FONDO1
@ 15,8  SAY FONDO1
@ 16,8  SAY $(FONDO,1,63)
@ 11,10 SAY "01  INSERIMENTO"
@ 12,10 SAY "02  MODIFICA"
@ 13,10 SAY "03  RICERCA"
@ 14,10 SAY "04  ORDINAMENTO"
@ 15,10 SAY "05  CANCELLAZIONE"
@ 11,40 SAY CHR(240)
@ 12,40 SAY CHR(240)
@ 13,40 SAY CHR(240)
@ 14,40 SAY CHR(240)
@ 15,40 SAY CHR(240)
@ 11,42 SAY "06  STAMPA"
@ 12,42 SAY "07  LISTATO"
@ 13,42 SAY "08  RICHIAMO CANCELLATI"
@ 14,42 SAY "09  ELIMINAZIONE CANCELLATI"
@ 15,42 SAY "10  FINE LAVORO"
STORE "  " TO SCELTA
@ 22,2  SAY "INTRODUCI IL NUMERO CORRISPONDENTE ALLA FUNZIONE SCELTA  "
@ 22,59 GET SCELTA PICTURE "99"
READ
DO PGOVR2
DO CASE
CASE SCELTA="01"
STORE 1 TO FLAG
DO PGINRC
LOOP
CASE SCELTA="02"
STORE 0 TO FLAG
DO PGINRC
LOOP
CASE SCELTA="03"
DO PGRICE
LOOP
CASE SCELTA="04"
DO PGORDI
LOOP
CASE SCELTA="05"
DO PGMARC
LOOP
CASE SCELTA="06"
DO PGSTAM
LOOP
CASE SCELTA="07"
DO PGLIST
LOOP
CASE SCELTA="08"
DO PGRICH
LOOP
CASE SCELTA="09"
DO PGERAS
LOOP
CASE SCELTA="10"
STORE "F" TO CICLO1
OTHERWISE
LOOP
ENDCASE
ENDDO
SET TALK ON
SET CONFIRM OFF
SET COLON ON
USE
RELEASE ALL
? CHR(2)
ERASE
POKE 71,0
RETURN

 CICLO1
OTHERWISE
LOOP
ENDCASE
ENDDO
SET TALK ON
SET CONFIRM OFF
SET COLON ON
USE
RELEASE ALL
? CHR(2)
ERASE
RETURN


@ 14,9  SAY "04  ORDINAMENTO"
@ 15,9  SAY "05"
@ 11,40 SAY "06AVANTI  CTRL+A=CAMPO INDIETRO  CTRL+V=INSERIMENTO"
CANCEL











,55 SAY CHR(203)
@ 22,64 SAY CHR(203)
@ 229 GET SCELTA PICTURE "99"
READ
DO PGOVR2
DO CASE
CASE SCELTA="01"
STORE 1 TO FLAG
DO PGINRC
LOOP
CASE SCELTA="02"
STORE 0 TO FLAG
DO PGINRC
LOOP
CASE SCELTA="03"
DO PGRICE
LOOP
CASE SCELTA="04"
DO PGORDI
LOOP
CASE SCELTA="05"
DO PGMARC
LOOP
CASE SCELTA="06"
DO PGSTAM
LOOP
CASE SCELTA="07"
DO PGLIST
LOOP
CASE SCELTA="08"
DO PGRICH
LOOP
CASE SCELTA9 GET SCELTA PICTURE "99"
READ
DO PGOVR2
DO CASE
CASE SCELTA="01"
STORE 1 TO FLAG
DO PGINRC
LOOP
CASE SCELTA="02"
STORE 0 TO FLAG
DO PGINRC
LOOP
CASE SCELTA="03"
DO PGRICE
LOOP
CASE SCELTA="04"
DO PGORDI
LOOP
CASE SCELTA="05"
DO PGMARC
LOOP
CASE SCELTA="06"
DO PGSTAM
LOOP
CASE SCELTA="07"
DO PGLIST
LOOP
CASE SCELTA="08"
DO PGRICH
LOOP
CASE SCELTA