;
; MDZ80 configuration file for boot_sys_offset_4E00.bin
; Generated by MDZ80 V0.9.0 on 2008/03/03 15:37
;
o 4E00		; program offset
i 0000-4DFF	; Invalid data
c 4E00-4F1E	; Code space
t 4F1F-4F5F	; ASCII text
c 4F60-4F74	; Code space
t 4F75-4F7D	; ASCII text
c 4F7E-4FC9	; Code space
