	TITLE	"Z33PRTYP - Z3lib 4.0
;=================================================================
;    Copyright (C) 1989 by Jay Sage.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
; Author  : Jay Sage
; Date    : 4/10/88
; Version : 1.0
; Module  : Z33PRTYP
; Abstract: This module contains the routine PRTTYPE which displays
;	the Type-3 or Type-4 load message of the form:
;		"(Type 3 at 8000H)"
;	The program type and load address are passed to the routine.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
; Module Entry Points

	PUBLIC		PRTTYPE

; External References

	EXT		PAFDC, PRINT, PHL4HC

	.Z80
	CSEG
;===============================================================
; NAME - PRTTYPE
; Entry: - None
; Exit : - None
; Uses : - None
; Special Requirements: None
;===============================================================

PRTTYPE: PUSH	HL		; Save load address

	CALL	PRINT
	DEFB	'(Type ',0

	CALL	PAFDC

	CALL	PRINT
	DEFB	' at ',0

	POP	HL
	PUSH	HL
	CALL	PHL4HC

	CALL	PRINT
	DEFB	'H)',0

	POP	HL
	RET

	END
