	TITLE	"Z3PMUSER - Z3lib 4.0"
;================================================================
;   The Libraries, Version 4, (C) 1989 by Alpha Systems Corp.
;----------------------------------------------------------------
; Author  : Harold F. Bower
;		Derived from Z3PMUSER.Z80 Ver 1.1 by Richard Conn
; Date    : 15 Mar 87
; Version : 1.2
; Module  : Z3PMUSER
; Abstract: This module contains the routine PUTMUSER which sets
;	the maximum legal user area into the Environment
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

;  Module Entry Points

	PUBLIC		PUTMUSER

;  External References

	EXT		@PUT0

	.Z80
	CSEG
;===============================================================
; NAME - PUTMUSER
; Entry:  A - Contains the value to set
; Exit : - None, the Max User # is set in Environment
; Uses : - None
; Special Requirements: None
;===============================================================

PUTMUSER: PUSH	HL		;save regs
	PUSH	DE
	PUSH	AF
	LD	DE,2DH		;pt to byte address
	JP	@PUT0		; ..Offset and save byte

	END
