;
; MDZ80 configuration file for basic_offset_4D00.bin
; Generated by MDZ80 V0.9.0 on 2008/02/29 14:07
;
o 4D00		; program offset
i 0000-4CFF	; Invalid data
c 4D00-4D94	; Code space
t 4D93-4DE8	; ASCII text
