;
; MDZ80 configuration file for sys13_sys_offset_4D00.bin
; Generated by MDZ80 V0.9.0 on 2008/03/02 22:09
;
o 4D00		; program offset
i 0000-4CFF	; Invalid data
c 4D00-4D20	; Code space
c 4D21		; Unknown - assumed code space
t 4D22-4F17	; ASCII text
c 4F18-4F19	; Code space
t 4F1A-4F55	; ASCII text
c 4F56-4F59	; Code space
t 4F5A-4FEB	; ASCII text
