;
; MDZ80 configuration file for sys7_offset_3240.bin
; Generated by MDZ80 V0.9.0 on 2015/09/23 23:46
;
o 3240		; program offset
i 0000-323F	; Invalid data
c 3240-326C	; Code space
i 326D-326E	; ignore data
i 326F		; ignore data
c 3270-383F	; Code space
b 3840		; 8-bit data
c 3841-3845	; Unknown - assumed code space
c 3846-3EEC	; Code space
b 3EED-3EEE	; 8-bit data
