	TITLE	"VIDK - Vlib 4.1"
	NAME	('VIDK')
;=================================================================
;  Copyright (C) 1989 by Harold F. Bower.  Permission granted to
; Alpha Systems Corp. to distribute with The Libraries, Version 4
;-----------------------------------------------------------------
; Author  : Harold F. Bower
; Date    : 4 Mar 89
; Version : 1.0
; Module  : VIDK
; Abstract:  This module contains the routine MCLS which clears
;	the Pull Down screen except for the menu bar.
; Revision:
;- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
;  Module Entry Points

	PUBLIC		MCLS

;  External References

	EXT		CLREOS, GOTOXY

	.Z80
	CSEG
;===============================================================
; MCLS - Clear Pull Down Menu screen
;  Entry: - None
;  Exit :  A = 0 and Zero Flag Set (Z) if Error
;	   A = FFH and Zero flag Reset (NZ) if Operation OK
;  Uses : AF
; Special Requirements: None
;===============================================================

MCLS:	PUSH	HL		; Save regs
	LD	HL,201H		; Clear from line 2, Col 1 to EOS
	CALL	GOTOXY
	CALL	CLREOS
	POP	HL
	RET

	END
