;
;=======================================================================
;
; CP/M 3 Z80 DarkStar (NE Z80) Porting
;
;=======================================================================
;;---------------------------------------------------------------------
;; Version      : 1.0 - 20140904
;; Assemble     : m80
;; Revisions:
;; 20140904	- Code start
;;---------------------------------------------------------------------
;
; Here just some common symbol...
;
	; SYSBIOS equates
	include	darkstar.equ

TRUE	EQU	-1
FALSE	EQU	0


	; determine if for bank select or not:
BANKED	EQU	TRUE		;< ... BANKED VERSION
ZPM3	EQU	TRUE		; ZPM3 build ?

	;
	; some other equs...
	;
CR	EQU     0DH		; CARRIAGE RETURN
LF	EQU     0AH		; LINE FEED;
FF	EQU	0CH		; FORM FEED (clear screen)


;
; COMMON.ASM [EOF]

