; Submitfile for generation of the biosinterface to the yaze-bios
;
; ---> Assemble source files
z80asm bioskrnl/f,ydrvtbl/f,yct/f,scb/f
; a:z80   bioskrnl/f,ydrvtbl/f,yct/f,scb/f
;
;
; ---> link the cpmldr
mera
linkdr cpml=cpmldr,bioskrnl,ydrvtbl,yct,scb
;
; following with zpm3ldr does not work - I don't know why !!
;mera
linkdr cpmlz=ZPM3LDR,bioskrnl,ydrvtbl,yct,scb
;

