	title	YAZE Control Table for the Modular CP/M	3.1 BIOS of yaze-ag
	subttl	Copyright (C) 2000,2002	Andreas	Gerlich
	page 65,132
;
; This file is part of yaze-ag - yet another Z80 emulator by ag.
;
; Copyright (C) 2002 Andreas Gerlich (Andreas.Gerlich@mathematik.uni-ulm.de)
;
; Yaze-ag is free software; you can redistribute it and/or modify it under
; the terms of the GNU General Public License as published by the Free
; Software Foundation; either version 2 of the License, or (at your
; option) any later version.
;
; This program is distributed in the hope that it will be useful, but
; WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
; General Public License for more details.
;
; You should have received a copy of the GNU General Public License
; along with this program (see the file COPYING);
; if not, write to the Free Software Foundation, Inc.,
; 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
;

	public	@YCT

	extrn	t$sssd

	extrn	?boot
	extrn	scb$base
	extrn	@dtbl
	extrn	dph0,dph1,dph2,dph3,dph4,dph5,dph6,dph7,dph8
	extrn	dph9,dph10,dph11,dph12,dph13,dph14,dph15

	maclib	sysdef
	;
	; MAXDSM  ; max blocks of storage capacity (defined in sysdef.lib)
	; MAXDRM  ; max numbers of directory entries (defined in sysdef.lib)

	;--------------------------------------------------------------
	DSEG		; banked memory
	;--------------------------------------------------------------

	dw	MAXDRM	; max reserved numbers of directory entries (yct-12)

	dw	MAXDSM	; max blocks of storage size (yct-10)

	dw	t$sssd	; address of translation table for SSSD disks (yct-8)

	dw	?boot	; address of bios_base (yct-6)

	dw	scb$base; address of System Control Block (yct-4)

	dw	@dtbl	; This pointer is nessassary, because the DPH pointers
			; in the YCT have the same entries as in the
			; @dtbl. But the entries in the @dtbl are change by
			; the yaze bios if the drive is presend or not. The
			; entries in the YCT above are never changed but
			; the YAZE-bios known about the DPHs if one is needed
			; to change it in the @dtbl.

	; This is identical with the @dtbl
	; It will be used by the yaze bios to set up the @dtbl if a drive
	; is presend or not.

@YCT:	dw	dph0	; A:	;<--- YAZE Control Table
	dw	dph1	; B:
	dw	dph2	; C:
	dw	dph3	; D:
	dw	dph4	; E:
	dw	dph5	; F:
	dw	dph6	; G:
	dw	dph7	; H:
	dw	dph8	; I:
	dw	dph9	; J:
	dw	dph10	; K:
	dw	dph11	; L:
	dw	dph12	; M:
	dw	dph13	; N:
	dw	dph14	; O:
	dw	dph15	; P:


	end
